services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "127.0.0.1:80:80"
    environment:
      - TZ=America/Mexico_City
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
    volumes:
      - ./.env:/var/www/html/.env:ro

  db:
    image: mysql:8.0
    restart: always
    environment:
      - TZ=America/Mexico_City
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - LANG=C.UTF-8
    volumes:
      - db_prod_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  db_prod_data: